name: Tirinha diária

on:
  workflow_dispatch:

  schedule:
    - cron: "0 11 * * *"


jobs:
  enviar:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4


      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Instalar bibliotecas
        run: |
          pip install -r requirements.txt


      - name: Executar script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

        run:
          python tirinha.py
